/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as IndexImport } from './routes/index'
import { Route as AdminRemoteImport } from './routes/_admin/_remote'
import { Route as AdminDashboardImport } from './routes/_admin/_dashboard'
import { Route as AdminRemoteIntegrateSendEnquiryRouteImport } from './routes/_admin/_remote/integrate/send-enquiry/route'
import { Route as AdminDashboardDashboardMyListRouteImport } from './routes/_admin/_dashboard/dashboard/my-list/route'
import { Route as AdminDashboardDashboardImportRouteImport } from './routes/_admin/_dashboard/dashboard/import/route'
import { Route as AdminDashboardDashboardEachRouteImport } from './routes/_admin/_dashboard/dashboard/each/route'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/route.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AdminRemoteRoute = AdminRemoteImport.update({
  id: '/_remote',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRemoteIntegrateSendEnquiryRouteRoute =
  AdminRemoteIntegrateSendEnquiryRouteImport.update({
    path: '/integrate/send-enquiry',
    getParentRoute: () => AdminRemoteRoute,
  } as any).lazy(() =>
    import('./routes/_admin/_remote/integrate/send-enquiry/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminDashboardDashboardMyListRouteRoute =
  AdminDashboardDashboardMyListRouteImport.update({
    path: '/dashboard/my-list',
    getParentRoute: () => AdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_admin/_dashboard/dashboard/my-list/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminDashboardDashboardImportRouteRoute =
  AdminDashboardDashboardImportRouteImport.update({
    path: '/dashboard/import',
    getParentRoute: () => AdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_admin/_dashboard/dashboard/import/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminDashboardDashboardEachRouteRoute =
  AdminDashboardDashboardEachRouteImport.update({
    path: '/dashboard/each',
    getParentRoute: () => AdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_admin/_dashboard/dashboard/each/route.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_admin/_dashboard': {
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/_admin/_remote': {
      preLoaderRoute: typeof AdminRemoteImport
      parentRoute: typeof AdminImport
    }
    '/_admin/_dashboard/dashboard/each': {
      preLoaderRoute: typeof AdminDashboardDashboardEachRouteImport
      parentRoute: typeof AdminDashboardImport
    }
    '/_admin/_dashboard/dashboard/import': {
      preLoaderRoute: typeof AdminDashboardDashboardImportRouteImport
      parentRoute: typeof AdminDashboardImport
    }
    '/_admin/_dashboard/dashboard/my-list': {
      preLoaderRoute: typeof AdminDashboardDashboardMyListRouteImport
      parentRoute: typeof AdminDashboardImport
    }
    '/_admin/_remote/integrate/send-enquiry': {
      preLoaderRoute: typeof AdminRemoteIntegrateSendEnquiryRouteImport
      parentRoute: typeof AdminRemoteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRouteRoute,
  AdminRoute.addChildren([
    AdminDashboardRoute.addChildren([
      AdminDashboardDashboardEachRouteRoute,
      AdminDashboardDashboardImportRouteRoute,
      AdminDashboardDashboardMyListRouteRoute,
    ]),
    AdminRemoteRoute.addChildren([AdminRemoteIntegrateSendEnquiryRouteRoute]),
  ]),
])

/* prettier-ignore-end */
